# Generated by Django 5.0.2 on 2024-05-29 19:35

import django.db.models.deletion
import gamespecs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name of the game directory')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='display name of the game')),
                ('short_description', models.CharField(max_length=300)),
                ('conclusion_system', models.CharField(choices=[('VD', 'Victory or Draw'), ('RB', 'Rank-based')], max_length=2)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('documentation', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=100)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameCodePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_preset_index', models.SmallIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('code_file', models.FileField(upload_to=gamespecs.models.GameCodePreset.get_code_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamespecs.gameinfo')),
            ],
        ),
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=gamespecs.models.GameTemplate.get_template_upload_path)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamespecs.gameinfo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gametemplate',
            constraint=models.UniqueConstraint(fields=('game', 'title'), name='game_template_unique_game_title'),
        ),
    ]
