# Generated by Django 5.0.2 on 2024-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamespecs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='has_scores',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
