# Generated by Django 5.0.2 on 2024-05-31 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0006_remove_fight_result'),
        ('gamespecs', '0002_gameinfo_has_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='fight',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='fights.fight'),
            preserve_default=False,
        ),
    ]
